# Podcast Generator Configuration
# --------------------------

# Logging Configuration
logging:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_output: true
  file_output: true

# Research Generation
research:
  provider: ollama  # ollama, openrouter, deepseek
  # openrouter google/gemini-2.0-flash-thinking-exp:free
  # ollama gemma3:1b
  model: gemma3:1b # For openrouter, use the full model path
  temperature: 0.7
  max_tokens: 1000
  character_limit: 1000  # Limits the size of the research output
  stream_tokens: true  # Enable token streaming in progress bar

# Transcript Generation
transcript:
  provider: ollama  # ollama, openrouter, deepseek
  model: gemma3:1b  # For openrouter, use the full model path
  temperature: 0.8
  max_tokens: 1000
  character_limit: 1000  # Limits the size of the transcript output
  stream_tokens: true  # Enable token streaming in progress bar
  
  # Speaker names that will appear in the transcript
  host_name: HOST
  expert_name: EXPERT
  beginner_name: BEGINNER

# Text-to-Speech
tts:
  provider: coqui  # elevenlabs, gemini, coqui
  
  # For ElevenLabs eleven_multilingual_v2
  model_id: eleven_multilingual_v2
  
  # Host voice settings
  host:
    # ElevenLabs settings
    voice_id: pNInz6obpgDQGcFmaJgB  # Adam (default)
    stability: 0.5  # 0.0-1.0: Higher stability = less variation but more consistent
    similarity_boost: 0.75  # 0.0-1.0: Higher similarity = closer to original voice
    
    # Gemini settings
    voice_name: en-US-Studio-O
    language_code: en-US
    gender: MALE
    speaking_rate: 1.0  # 0.25-4.0: 1.0 is normal speed
    pitch: 0.0  # -20.0-20.0: 0.0 is normal pitch

    # Coqui settings (vocoder auto-selected)
    model: tts_models/en/ljspeech/tacotron2-DDC
    speaker: # Optional speaker ID if using multi-speaker model
    # language: en  # Only needed for multilingual models
  
  # Expert voice settings
  expert:
    # ElevenLabs settings
    voice_id: EXAVITQu4vr4xnSDxMaL  # Sarah (default)
    stability: 0.6
    similarity_boost: 0.8
    
    # Gemini settings
    voice_name: en-US-Neural2-D
    language_code: en-US
    gender: MALE
    speaking_rate: 0.95
    pitch: -1.0

    # Coqui settings (vocoder auto-selected)
    model: tts_models/en/ljspeech/tacotron2-DDC
    speaker: # Optional speaker ID if using multi-speaker model
    language: en
  
  # Beginner voice settings
  beginner:
    # ElevenLabs settings
    voice_id: yoZ06aMxZJJ28mfd3POQ  # Rachel (default)
    stability: 0.4
    similarity_boost: 0.7
    
    # Gemini settings
    voice_name: en-US-Neural2-F
    language_code: en-US
    gender: FEMALE
    speaking_rate: 1.05
    pitch: 2.0

    # Coqui settings (vocoder auto-selected)
    model: tts_models/en/ljspeech/tacotron2-DDC
    speaker: # Optional speaker ID if using multi-speaker model
    language: en

# Audio Assembler
assembler:
  # Audio quality settings
  sample_rate: 44100  # Hz
  bitrate: "128k"
  normalize_volume: true
  target_dBFS: -16  # Target loudness level (dB)
  
  # Optional background music
  intro_music: ""  # Path to intro music file (optional)
  outro_music: ""  # Path to outro music file (optional)
  
  # Music fade settings (in milliseconds)
  intro_fade_in: 1000
  intro_fade_out: 2000
  silence_after_intro: 1000
  outro_fade_in: 2000
  outro_fade_out: 5000
  silence_before_outro: 1000

# API URLs (can be modified if API endpoints change)
api_urls:
  ollama: http://localhost:11434/api/generate
  openrouter: https://openrouter.ai/api/v1/chat/completions
  deepseek: https://api.deepseek.com/v1/chat/completions
  elevenlabs: https://api.elevenlabs.io/v1/text-to-speech
  gemini: https://texttospeech.googleapis.com/v1/text:synthesize
  referer: http://localhost

# API Timeout Settings (in seconds)
api_timeouts:
  ollama_research: 300  # 5 minutes for research generation
  ollama_transcript: 600  # 10 minutes for transcript generation
  openrouter: 180  # 3 minutes for OpenRouter calls
  deepseek: 180  # 3 minutes for DeepSeek calls
  elevenlabs: 60  # 1 minute for ElevenLabs calls

# API Statistics Tracking
api_stats:
  enabled: true
  directory: data/api_stats  # Directory to store API usage statistics
  # Request retry settings
  max_retries: 3  # Maximum number of retries for failed API requests
  retry_delay: 2  # Base delay in seconds between retries (exponential backoff is applied)
  # Alert thresholds
  error_alert_threshold: 5  # Alert if more than this many errors occur
